---
title: "Hawkes Process evaluation"
output: html_document
date: "2025-01-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# source("simetasmay2017.r")
```

```{r}
hawkes_unif_background_sampling = function(mu, phi, T_max) {
  t = rexp(1, mu)
  out = c(t)
  lambda_max = mu + phi(0)
  while(t < T_max) {
    accepted = FALSE
    while(!accepted) {
      t_next = t + rexp(1, lambda_max)
      intensity = mu + sum(phi(t_next - out))
      u = runif(1)
      if(u < intensity/lambda_max){
        t = t_next
        accepted = TRUE
      }
    }
    if(t < T_max){
      out = c(out, t)
    }
  }
  out
}

plot_hawkes_intensity = function(obs, mu, phi, T_max, x_freq = .005, get_vals = FALSE){
  x = seq(0, T_max, x_freq)
  f = lapply(x, function(u){mu + sum(phi(u - obs[which(obs <= u)]))})
  if(get_vals){
    return(list("t" = x, "intensity" = f)) 
  } else {
    plot(x, f, type = "l")
  }
}

plot_average_intensity = function(mu, phi, T_max, num_replicates = 1000, x_freq = .005, get_vals = FALSE){
  events = replicate(num_replicates, hawkes_unif_background_sampling(mu, phi, T_max))
  intensities = lapply(events, function(x){plot_hawkes_intensity(x, mu, phi, T_max, x_freq, get_vals = TRUE)[["intensity"]]})
  intensities = matrix(unlist(intensities), ncol = num_replicates)
  mean_intensities = apply(intensities, MARGIN = 1, mean)
  t = seq(0, T_max, x_freq)
  if(get_vals){
    return(list("t" = t, "intensity" = mean_intensities))
  } else {
    plot(t, mean_intensities, type = "l")
  }
}

hawkes_unif_background_likelihood = function(obs, mu, phi, T_max) {
  
}
```

```{r}
set.seed(123)
mu = 1
a = 0.5
b = 1
K = 0.5
T_max = 100
phi = function(t){
  a * b * exp(-b*t)
}

res = hawkes_unif_background_sampling(mu, phi, T_max)
plot_hawkes_intensity(res, mu, phi, T_max)
```

```{r}
plot_average_intensity(mu, phi, T_max)
```

```{r}
library(stpphawkes)
library(hawkesbow)
library(mosaic)
```

```{r}
set.seed(1234)
mu = 1
alpha = 0.5
beta = 1
T_max = 10
res = hawkes(T_max, fun=mu, repr=alpha, family="exp", rate=beta)
```

```{r}
plot(res, intensity = TRUE)
plot(res, intensity = FALSE)
```

```{r}
mcmc_param <- list(n_mcmc = 30000, n_burn = 20000, sig_mu = 0.5, 
            sig_alpha = 0.5, sig_beta = 0.5, mu_param = c(0.1, 
                0.1), alpha_param = c(0.1, 0.1), beta_param = c(0.1, 
                0.1))

mcmc_est = mcmc_temporal(res$p, t_max = T_max, mcmc_param = mcmc_param)
```

```{r}
mean(mcmc_est$samps$mu)
mean(mcmc_est$samps$alpha)
mean(mcmc_est$samps$beta)
```

```{r}
mle_est = temporal.mle(res$p, t_max = T_max, print = FALSE)
```

```{r}
mle_est$mu
mle_est$alpha
mle_est$beta
```


```{r}
miss = c()
t_mis = c()
for(i in length(res):1) {
  if(runif(1) < .1) {
    miss = c(miss, res[i])
    res_before = ifelse(i == 1, 0, res[i - 1])
    res_after = ifelse(i == length(res), T_max, res[i + 1])
    t_mis = c(t_mis, res_before, res_after)
    res = res[-i]
  }
}
t_mis = matrix(t_mis, ncol = 2, byrow = TRUE)

# Combine consecutive segments with deleted data
for(i in (nrow(t_mis) - 1):1) {
  if(t_mis[i, 2] == t_mis[i + 1, 2]) {
    t_mis = t_mis[-i,]
  }
}
```

```{r}
t_mis
```


```{r}
mcmc_est_full_data = mcmc_temporal(res, t_max = T_max)
```
```{r}
mean(mcmc_est_full_data$mu)
mean(mcmc_est_full_data$alpha)
mean(mcmc_est_full_data$beta)
```
```{r}
mle_est_full_data = temporal.mle(res, t_max = T_max, print = FALSE)
```

```{r}
mean(mle_est_full_data$mu)
mean(mle_est_full_data$alpha)
mean(mle_est_full_data$beta)
```

```{r}
mcmc_est_interpolate_gaps = mcmc_temporal(res, t_max = T_max, t_mis = t_mis)
```

```{r}
mean(mcmc_est_interpolate_gaps$mu)
mean(mcmc_est_interpolate_gaps$alpha)
mean(mcmc_est_interpolate_gaps$beta)
```

```{r}
length(miss)
mean(mcmc_est_interpolate_gaps$z)
```


```{r}
for(i in 1:10) {
  print(tally(mcmc_est$branching[i,], format = "proportion"))
}
```
```{r}
trigger = function(d) {
  alpha * beta * exp(-beta * d)
}

for(i in 2:10) {
  print(c(mu, trigger(res$p[i] - res$p[1:(i-1)])) / sum(c(mu, trigger(res$p[i] - res$p[1:(i-1)]))))
}
```

```{r}
rand_dat = hawkes(50, 2, 0.5, function(n){rnorm(n, 5, 1)})
y = discrete(rand_dat, binsize = 1)
whittle(y, "Gaussian")
```


